<a href="https://colab.research.google.com/github/lexiwellen/Data-Science/blob/main/Wellen_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [114]:
import numpy as np
import matplotlib.pyplot as plt

# Loops

In [115]:
for i in range(420):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [116]:
for i in range(5,8):
    print(i)

5
6
7


In [117]:
for i in range(3):
    print( "Test Number: " ,i )

Test Number:  0
Test Number:  1
Test Number:  2


In [118]:
# this is set up to give you the squared value of any number

In [119]:
def square(x):
    return x**2

In [120]:
square(5)

25

In [121]:
square(420)

176400

In [122]:
square(123456789)

15241578750190521

In [123]:
square(square(square(2)))

256

In [124]:
def add_two(x):
    return x+2

In [125]:
add_two(5)

7

In [126]:
square(add_two(5))

49

In [127]:
# = is assignment operator, make up a meory box and store whatever is after 

In [128]:
# == is a logical eqaution so youre recieving one of two answers

In [129]:
if choice =="apple":

    print("You chose apples.")
    print("Thank you, shop again soon!")
elif choice == "orange":

    print("You chose oranges.")  

else:
    print("You did not choose apples or oranges.")

       

You chose apples.
Thank you, shop again soon!


In [130]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): apple


In [131]:
choice

'apple'

In [132]:
np.random.permutation(52)

array([20, 27, 47, 16,  0, 19,  4, 51, 12, 49, 18, 34, 28, 39, 21, 13, 50,
        2, 48,  7, 42, 41, 26, 36, 22, 15,  5, 46, 31, 45, 23,  6, 30,  8,
       24, 25, 11, 35,  9, 40, 32, 44, 38, 17, 33,  1,  3, 37, 43, 14, 29,
       10])

In [133]:
cards = np.random.permutation(52)

In [134]:
cards

array([43, 44, 12, 37, 23, 11, 31, 18,  7, 27, 51,  0, 34,  1, 29, 42, 19,
        6, 24, 14, 28, 32, 20, 40, 22, 26, 33, 47, 35, 38, 49,  8,  3, 48,
       50, 13, 41,  9,  2, 45, 36, 46, 21, 39, 15, 30,  5, 25, 10, 17, 16,
        4])

In [135]:
cards[0]

43

In [136]:
cards[32]

3

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [137]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [138]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [139]:
# this gives us the remainder

In [140]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [141]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [142]:
def card_name(card_number):

  suit = card_number//13
  name = card_number%13

  return names[name] + " of " +suits[suit]

In [143]:
card_name(6)

'Seven of Clubs'

In [144]:
card_name(51)

'King of Diamonds'

In [145]:
top_of_deck           = card_name(cards[0])
second_card_in_deck   = card_name(cards[1]) 
last_card_in_deck     = card_name(cards[-1])

In [146]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Five of Diamonds', 'Six of Diamonds', 'Five of Clubs')

In [147]:
for i in range(5):
     print(card_name(cards[i]))

Five of Diamonds
Six of Diamonds
King of Clubs
Queen of Hearts
Jack of Spades


In [148]:
# many idfferent options to use for a card trick

In [149]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11"
card_url_tail = ".png"

In [150]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [151]:
from IPython.core.display import display, HTML

In [152]:
def show_img(img):
    display(HTML('<img src=' + img + '>'))

In [156]:
img = card_url_head + suit[i] + card[j] + card_url_tail

IndexError: ignored